version: '3.1'

services:
  qbittorrent:
    image: linuxserver/qbittorrent
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - UMASK_SET=022 #optional
      - WEBUI_PORT=8081
    volumes:
      - qbittorrent:/config
      - downloads:/downloads
    restart: unless-stopped
    depends_on:
      - wireguard
    network_mode: "service:wireguard"



  wireguard:
    image: ghcr.io/linuxserver/wireguard
    container_name: wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    volumes:
      - wireguard:/config
    ports:
      - 51820:51820/udp
      - 6881:6881
      - 6881:6881/udp
      - 8080:8080
      - 8081:8081
    networks:
      - wireguard-torrent



    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    restart: unless-stopped
    networks:
      wireguard-torrent:
        ipv4_address: 192.168.0.25


networks:
  wireguard-torrent:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.10.0/24
          gateway: 192.168.10.1
          ip_range: 192.168.10.2/10

volumes:
  wireguard:
    external: true
  qbittorrent:
    external: true
  downloads:
    external: true
    
