version: "3"

networks:
  gitea:
    external: false

services:
  server:
    image: gitea/gitea:1.21.3
    container_name: gitea
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - GITEA__database__DB_TYPE=postgres
      - GITEA__database__HOST=db:5432
      - GITEA__database__NAME=gitea
      - GITEA__database__USER=gitea
      - GITEA__database__PASSWD=gitea
    restart: always
    networks:
      - gitea
    volumes:
      - gitea:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "3333:3000"
      - "222:22"
    depends_on:
      - db

  db:
    image: postgres:14
    restart: always
    environment:
      - POSTGRES_USER=gitea
      - POSTGRES_PASSWORD=gitea
      - POSTGRES_DB=gitea
    networks:
      - gitea
    volumes:
      - gitea-postgress:/var/lib/postgresql/data

  runner:
    image: gitea/act_runner:nightly
    environment:
      CONFIG_FILE: /config/config.yaml
      GITEA_INSTANCE_URL: "https://git.evanc.dev"
      GITEA_RUNNER_REGISTRATION_TOKEN: "UKfvwl6ADR4jWb2UOS25fiEOQ7SCXaCSSgC5ctHr"
      GITEA_RUNNER_NAME: "main"
      GITEA_RUNNER_LABELS: "main"
    volumes:
      - gitea-runner-config:/config
      - gitea-runner:/data
      - /var/run/docker.sock:/var/run/docker.sock




volumes:
  gitea-postgress:
    external: true
  gitea:
    external: true
  gitea-runner:
    external: true
  gitea-runner-config:
    external: true